steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'lint']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'gcloud:test']

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
    '.'
  ]

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', './deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-d'
  - 'CLOUDSDK_CONTAINER_CLUSTER=flight-status-cluster'

images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'