apiVersion: v1
kind: Service
metadata:
  name: flight-status-service
  labels:
    app: flight-status
    tier: frontend
spec:
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: flight-status
  type: LoadBalancer
---
apiVersion: apps/v1beta2
kind: Deployment 
metadata:
  name: flight-status-deployment
spec:
  selector:
    matchLabels:
      app: flight-status
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flight-status
        tier: frontend
    spec:
      containers:
      - name: flight-status-container
        image: gcr.io/flight-status-204918/flight-status:latest
        ports:
        - name: http-server
          containerPort: 8080